const COPY = {
  terms: {
    ko: { eyebrow: 'MVP 이용약관', title: '서비스 이용 원칙', sections: [['서비스 목적', 'FACt.Smack은 사진과 질문에 대한 참여자의 주관적 평가를 모아 보여주는 서비스입니다. 결과는 사실·의료·전문적 판단이 아닌 참고용 피드백입니다.'], ['가입 자격', '공개 MVP는 만 14세 이상만 이용할 수 있습니다. 법정대리인 동의가 필요한 만 14세 미만 아동은 가입할 수 없습니다.'], ['회원의 책임', '본인이 촬영했거나 공개·사용 권한을 가진 사진만 올릴 수 있습니다. 타인의 개인정보, 혐오·괴롭힘·성적 대상화 또는 불법 콘텐츠는 올릴 수 없습니다.'], ['콘텐츠 처리', '운영자는 신고 또는 정책 위반이 확인된 게시물을 숨기거나 삭제할 수 있습니다.'], ['MVP 범위', '공개 MVP 기간에는 기능과 정책이 개선될 수 있으며, 중요한 변경은 서비스 안에서 알립니다.']] },
    en: { eyebrow: 'MVP TERMS', title: 'How this service works', sections: [['Purpose', 'FACt.Smack collects subjective feedback on photos and questions. Results are reference feedback, not factual, medical, or professional judgments.'], ['Eligibility', 'The public MVP is available only to people aged 14 or older. Children under 14 who require verified parental consent may not create an account.'], ['Member responsibility', 'Only upload photos you created or have permission to use. Do not upload personal data, hateful, harassing, sexualizing, or unlawful content.'], ['Content handling', 'We may hide or remove posts when a report or policy violation requires it.'], ['MVP scope', 'Features and policies may improve during the public MVP. Material changes will be announced in the service.']] },
  },
  privacy: {
    ko: { eyebrow: '개인정보 처리 안내', title: '어떤 정보를 왜 다루나요', sections: [['처리 항목', '인증에 필요한 계정 정보, 공개 아이디와 프로필 사진, 업로드한 미디어·게시물, 평가·댓글·팔로우·차단·스크랩, 신고·검토 기록을 처리합니다. 약관 동의와 사진·영상 권리 확인의 문서 버전·확인 시각도 기록합니다.'], ['브라우저 저장', '로그인 유지 선택에 따라 인증 세션을 브라우저의 로컬 또는 세션 저장소에 보관합니다. 이메일 인증 진행값, 언어 선택, 서비스 분석 이벤트와 임시 세션 식별자도 브라우저에 저장될 수 있습니다.'], ['언어 제안', '첫 방문에는 Vercel이 요청의 IP 주소에서 제공하는 국가 코드로 화면 언어를 제안할 수 있습니다. FACS는 이 언어 선택을 위해 IP 주소 원문을 저장하지 않습니다. 언어는 언제든 직접 바꿀 수 있습니다.'], ['사용 통계', '서비스 개선을 위해 GA4로 방문과 기능 완료 이벤트를 측정합니다. GA4는 이용자·세션 구분을 위해 쿠키(_ga 등)를 사용하며 브라우저·기기 정보와 대략적인 위치 정보가 수집될 수 있습니다. 전송하는 기능 이벤트는 정해진 이름으로 제한하고 방문 주소는 사이트 첫 화면 주소로 지정합니다. 광고 개인화와 Google Signals는 사용하지 않습니다.'], ['이용 목적', '인증·피드 제공·평가 집계·신고 검토·부정 이용 방지와 서비스 품질 개선에 사용합니다.'], ['공개 범위', '차단되지 않은 로그인 회원은 공개 아이디·프로필 사진·소개 문구를 볼 수 있습니다. 게시물·미디어·댓글은 전체 공개 또는 팔로워만 공개 설정과 차단 상태에 따라 표시됩니다. 전체 공개 게시물의 사진 한 장이 로그인 전 화면에 작성자 정보 없이 표시될 수도 있습니다. 이메일과 로그인 제공자 정보는 다른 회원에게 표시하지 않습니다.'], ['보관과 삭제', '작성자가 게시물이나 댓글을 삭제하면 해당 원본을 제거합니다. 게시물에 연결된 미디어·평가·댓글도 함께 삭제됩니다. 신고·검토 기록과 백업 사본은 별도로 남을 수 있습니다. 계정 탈퇴는 현재 지원하지 않습니다.'], ['요청과 문의', '열람·정정·삭제·처리정지 및 개인정보 문의는 teamfactsmack@gmail.com으로 접수합니다. 요청자 확인과 실제 처리 가능 범위를 안내한 뒤 처리합니다.'], ['아동의 개인정보', '법정대리인 동의 확인 기능이 없어 만 14세 미만 아동의 가입을 허용하지 않습니다.']] },
    en: { eyebrow: 'PRIVACY NOTICE', title: 'What we handle and why', sections: [['Data we handle', 'We process account data needed for authentication, public handles and profile photos, uploaded media and posts, ratings, comments, follows, blocks, scraps, and report and review records. We also record the document version and confirmation time for Terms acceptance and photo or video rights confirmation.'], ['Browser storage', 'Depending on your keep-me-signed-in choice, we store the authentication session in browser local or session storage. Pending email verification, language choice, product analytics events, and a temporary session identifier may also be stored in the browser.'], ['Language suggestion', 'On a first visit, Vercel may use a country code derived from the request IP address to suggest the interface language. FACS does not store the raw IP address for this language choice. You can change the language at any time.'], ['Usage analytics', 'We use GA4 to measure visits and completed feature events. GA4 uses cookies (including _ga) to distinguish users and sessions, and may collect browser, device, and approximate location information. We limit feature events to fixed names and set the reported page URL to the site home page. Advertising personalization and Google Signals are disabled.'], ['Purpose', 'We use this data for authentication, feed delivery, aggregate results, report review, abuse prevention, and service quality.'], ['What is public', 'Signed-in members who are not blocked can see your public handle, profile photo, and bio. Posts, media, and comments are shown according to the public or followers-only setting and block status. One image from a public post may also appear on the signed-out screen without author details. Your email and login provider are not shown to other members.'], ['Retention and deletion', 'When an author deletes a post or comment, its original record is removed. Attached media, ratings, and comments are deleted too. Report and review records, as well as backup copies, may remain separately. Account closure is not currently supported.'], ['Requests and contact', 'Send access, correction, deletion, restriction, or privacy requests to teamfactsmack@gmail.com. We verify the requester and explain the available handling before acting.'], ['Children', 'Because verified parental consent is not supported, children under 14 may not create an account.']] },
  },
  safety: {
    ko: { eyebrow: '안전·신고 기준', title: '존중하는 평가를 위한 기준', sections: [['허용하지 않는 콘텐츠', '스팸·사기, 혐오·차별, 괴롭힘·욕설, 성적 콘텐츠, 개인정보 노출, 타인 비방, 사회 통념 위반을 허용하지 않습니다.'], ['신고와 검토', '로그인 회원은 게시물을 신고할 수 있으며, 운영자는 신고 사유와 게시물 미리보기를 검토해 신고 적용 또는 신고 반려를 처리합니다.'], ['차단', '차단하면 양쪽의 게시물·프로필·팔로우 관계와 상호작용이 즉시 숨겨집니다.'], ['긴급한 위험', '즉각적인 위험이나 범죄 상황에서는 서비스 신고보다 지역 긴급기관에 먼저 연락해 주세요.']] },
    en: { eyebrow: 'SAFETY & REPORTING', title: 'Standards for respectful feedback', sections: [['Not allowed', 'Spam or fraud, hate or discrimination, harassment, sexual content, exposed personal information, defamation, and socially harmful content are not allowed.'], ['Reports and review', 'Signed-in members can report a post. Staff review the reason and preview, then apply or dismiss the report.'], ['Blocking', 'Blocking immediately hides each member’s posts, profiles, follow relationship, and interactions from the other.'], ['Urgent danger', 'For immediate danger or crime, contact local emergency services before using in-service reporting.']] },
  },
};

export default function LegalPolicyDialog({ type = 'terms', locale = 'ko', onClose }) {
  const korean = locale !== 'en';
  const copy = COPY[type]?.[korean ? 'ko' : 'en'] ?? COPY.terms[korean ? 'ko' : 'en'];
  return <div className="fixed inset-0 z-[80] flex items-end justify-center bg-black/55 p-3 sm:items-center" onClick={onClose}>
    <section role="dialog" aria-modal="true" aria-labelledby="legal-policy-title" className="max-h-[82dvh] w-full max-w-lg overflow-y-auto rounded-xl bg-[#fbf9f4] text-[#1b1c19] shadow-2xl" onClick={(event) => event.stopPropagation()}>
      <header className="sticky top-0 flex items-start justify-between border-b border-[#e4e2dd] bg-[#fbf9f4] px-5 py-4">
        <div><p className="text-[10px] font-bold tracking-[0.14em] text-[#8a7000]">{copy.eyebrow}</p><h1 id="legal-policy-title" className="mt-1 text-lg font-bold">{copy.title}</h1></div>
        <button type="button" onClick={onClose} aria-label={korean ? '정책 화면 닫기' : 'Close policy'} className="flex h-8 w-8 items-center justify-center rounded-full border border-[#d7d1c5] text-[#575850]"><span className="material-symbols-outlined text-base" aria-hidden="true">close</span></button>
      </header>
      <div className="space-y-5 px-5 py-5">{copy.sections.map(([heading, body]) => <section key={heading}><h2 className="text-sm font-bold">{heading}</h2><p className="mt-1.5 text-sm leading-6 text-[#5f625e]">{body}</p></section>)}</div>
      <footer className="border-t border-[#e4e2dd] px-5 py-3 text-[10px] leading-relaxed text-[#7b7d78]">
        <p>{korean ? '운영 주체: Tweety and Company' : 'Operator: Tweety and Company'} · {korean ? '개인정보 보호책임자: Joon (Manager)' : 'Privacy Officer: Joon (Manager)'}</p>
        <p>{korean ? '문의: ' : 'Contact: '}<a href="mailto:teamfactsmack@gmail.com" className="underline">teamfactsmack@gmail.com</a></p>
        <p className="mt-1">{korean ? '시행일: 2026년 10월 9일' : 'Effective: October 9, 2026'}</p>
      </footer>
    </section>
  </div>;
}
